# Reg_no:D057

In [ ]:
import numpy as np
import pandas as pd

In [ ]:

student = {'name':['tolu', 'sola','caro','yusuf','bola','yinka','funmi', 'adams','ajayi','paul'],
           'relationship':['single','single','married','single','single','married','single','single','married','married'],
           'age':[23,22,21,25,27,28,30,25,22,18],
           'department':['chemistry', 'law','biology','english','data','agric','politics','computer','physics','sport']}

      
type(student)

dict

In [ ]:
student

{'age': [23, 22, 21, 25, 27, 28, 30, 25, 22, 18],
 'department': ['chemistry',
  'law',
  'biology',
  'english',
  'data',
  'agric',
  'politics',
  'computer',
  'physics',
  'sport'],
 'name': ['tolu',
  'sola',
  'caro',
  'yusuf',
  'bola',
  'yinka',
  'funmi',
  'adams',
  'ajayi',
  'paul'],
 'relationship': ['single',
  'single',
  'married',
  'single',
  'single',
  'married',
  'single',
  'single',
  'married',
  'married']}

In [ ]:
student['cgpa'] = [4.0,3.0,3.2,2.3,5.0,2.2,4.3,4.7,4.2,1.0] 

student

{'age': [23, 22, 21, 25, 27, 28, 30, 25, 22, 18],
 'cgpa': [4.0, 3.0, 3.2, 2.3, 5.0, 2.2, 4.3, 4.7, 4.2, 1.0],
 'department': ['chemistry',
  'law',
  'biology',
  'english',
  'data',
  'agric',
  'politics',
  'computer',
  'physics',
  'sport'],
 'name': ['tolu',
  'sola',
  'caro',
  'yusuf',
  'bola',
  'yinka',
  'funmi',
  'adams',
  'ajayi',
  'paul'],
 'relationship': ['single',
  'single',
  'married',
  'single',
  'single',
  'married',
  'single',
  'single',
  'married',
  'married']}

In [ ]:
student.pop('relationship')

['single',
 'single',
 'married',
 'single',
 'single',
 'married',
 'single',
 'single',
 'married',
 'married']

In [ ]:
student

{'age': [23, 22, 21, 25, 27, 28, 30, 25, 22, 18],
 'cgpa': [4.0, 3.0, 3.2, 2.3, 5.0, 2.2, 4.3, 4.7, 4.2, 1.0],
 'department': ['chemistry',
  'law',
  'biology',
  'english',
  'data',
  'agric',
  'politics',
  'computer',
  'physics',
  'sport'],
 'name': ['tolu',
  'sola',
  'caro',
  'yusuf',
  'bola',
  'yinka',
  'funmi',
  'adams',
  'ajayi',
  'paul']}

In [ ]:
df = pd.DataFrame(student)

In [ ]:
df

name  age department  cgpa
0   tolu   23  chemistry   4.0
1   sola   22        law   3.0
2   caro   21    biology   3.2
3  yusuf   25    english   2.3
4   bola   27       data   5.0
5  yinka   28      agric   2.2
6  funmi   30   politics   4.3
7  adams   25   computer   4.7
8  ajayi   22    physics   4.2
9   paul   18      sport   1.0

In [ ]:
df['admission_date'] = ['2012-12-2','2010-4-4','2020-2-3','2014-3-6','2020-12-5','2015-10-4','2013-12-4','2020-3-6','2020-12-8','20-12-4']
df['gender'] =['male','female','male','female','female','male','female','male','female','male']

In [ ]:
df

name  age department  cgpa admission_date  gender
0   tolu   23  chemistry   4.0      2012-12-2    male
1   sola   22        law   3.0       2010-4-4  female
2   caro   21    biology   3.2       2020-2-3    male
3  yusuf   25    english   2.3       2014-3-6  female
4   bola   27       data   5.0      2020-12-5  female
5  yinka   28      agric   2.2      2015-10-4    male
6  funmi   30   politics   4.3      2013-12-4  female
7  adams   25   computer   4.7       2020-3-6    male
8  ajayi   22    physics   4.2      2020-12-8  female
9   paul   18      sport   1.0        20-12-4    male

In [ ]:
name =['tolu', 'sola','caro','yusuf','bola','yinka','funmi', 'adams','ajayi','paul']
age= [23,22,21,25,27,28,30,25,22,18]
department= ['chemistry', 'law','biology','english','data','agric','politics','computer','physics','sport']
admission_date = ['2012-12-2','2010-4-4','2020-2-3','2014-3-6','2020-12-5','2015-10-4','2013-12-4','2020-3-6','2020-12-8','20-12-4']
gender =['male','female','male','female','female','male','female','male','female','male']

df2= pd.DataFrame({'name':name,'age':age,'department':department,'admission_date':admission_date,'gender':gender})

In [ ]:
df2

name  age department admission_date  gender
0   tolu   23  chemistry      2012-12-2    male
1   sola   22        law       2010-4-4  female
2   caro   21    biology       2020-2-3    male
3  yusuf   25    english       2014-3-6  female
4   bola   27       data      2020-12-5  female
5  yinka   28      agric      2015-10-4    male
6  funmi   30   politics      2013-12-4  female
7  adams   25   computer       2020-3-6    male
8  ajayi   22    physics      2020-12-8  female
9   paul   18      sport        20-12-4    male

In [ ]:
df

name  age department  cgpa admission_date  gender
0   tolu   23  chemistry   4.0      2012-12-2    male
1   sola   22        law   3.0       2010-4-4  female
2   caro   21    biology   3.2       2020-2-3    male
3  yusuf   25    english   2.3       2014-3-6  female
4   bola   27       data   5.0      2020-12-5  female
5  yinka   28      agric   2.2      2015-10-4    male
6  funmi   30   politics   4.3      2013-12-4  female
7  adams   25   computer   4.7       2020-3-6    male
8  ajayi   22    physics   4.2      2020-12-8  female
9   paul   18      sport   1.0        20-12-4    male

In [ ]:
import datetime as dt

In [ ]:
df['admission_date']= pd.to_datetime(df['admission_date'])

df.dtypes

name                      object
age                        int64
department                object
cgpa                     float64
admission_date    datetime64[ns]
gender                    object
dtype: object

In [ ]:
df['year']=df['admission_date'].dt.year

In [ ]:
df

name  age department  cgpa admission_date  gender  year
0   tolu   23  chemistry   4.0     2012-12-02    male  2012
1   sola   22        law   3.0     2010-04-04  female  2010
2   caro   21    biology   3.2     2020-02-03    male  2020
3  yusuf   25    english   2.3     2014-03-06  female  2014
4   bola   27       data   5.0     2020-12-05  female  2020
5  yinka   28      agric   2.2     2015-10-04    male  2015
6  funmi   30   politics   4.3     2013-12-04  female  2013
7  adams   25   computer   4.7     2020-03-06    male  2020
8  ajayi   22    physics   4.2     2020-12-08  female  2020
9   paul   18      sport   1.0     2004-12-20    male  2004

In [ ]:
df['month']=df['admission_date'].dt.month

In [ ]:
df

name  age department  cgpa admission_date  gender  year  month
0   tolu   23  chemistry   4.0     2012-12-02    male  2012     12
1   sola   22        law   3.0     2010-04-04  female  2010      4
2   caro   21    biology   3.2     2020-02-03    male  2020      2
3  yusuf   25    english   2.3     2014-03-06  female  2014      3
4   bola   27       data   5.0     2020-12-05  female  2020     12
5  yinka   28      agric   2.2     2015-10-04    male  2015     10
6  funmi   30   politics   4.3     2013-12-04  female  2013     12
7  adams   25   computer   4.7     2020-03-06    male  2020      3
8  ajayi   22    physics   4.2     2020-12-08  female  2020     12
9   paul   18      sport   1.0     2004-12-20    male  2004     12

In [ ]:
df['day']=df['admission_date'].dt.day

In [ ]:
df

name  age department  cgpa admission_date  gender  year  month  day
0   tolu   23  chemistry   4.0     2012-12-02    male  2012     12    2
1   sola   22        law   3.0     2010-04-04  female  2010      4    4
2   caro   21    biology   3.2     2020-02-03    male  2020      2    3
3  yusuf   25    english   2.3     2014-03-06  female  2014      3    6
4   bola   27       data   5.0     2020-12-05  female  2020     12    5
5  yinka   28      agric   2.2     2015-10-04    male  2015     10    4
6  funmi   30   politics   4.3     2013-12-04  female  2013     12    4
7  adams   25   computer   4.7     2020-03-06    male  2020      3    6
8  ajayi   22    physics   4.2     2020-12-08  female  2020     12    8
9   paul   18      sport   1.0     2004-12-20    male  2004     12   20

In [ ]:
df['hour']=df['admission_date'].dt.hour
df

In [ ]:
df.dtypes

name                      object
age                        int64
department                object
cgpa                     float64
admission_date    datetime64[ns]
gender                    object
year                       int64
month                      int64
day                        int64
dtype: object

In [ ]:
df.isnull()

name    age  department   cgpa  admission_date  gender   year  month  \
0  False  False       False  False           False   False  False  False   
1  False  False       False  False           False   False  False  False   
2  False  False       False  False           False   False  False  False   
3  False  False       False  False           False   False  False  False   
4  False  False       False  False           False   False  False  False   
5  False  False       False  False           False   False  False  False   
6  False  False       False  False           False   False  False  False   
7  False  False       False  False           False   False  False  False   
8  False  False       False  False           False   False  False  False   
9  False  False       False  False           False   False  False  False   

     day  
0  False  
1  False  
2  False  
3  False  
4  False  
5  False  
6  False  
7  False  
8  False  
9  False

In [ ]:
df.isnull().percentage()

AttributeError: ignored

In [ ]:
df

name  age department  cgpa admission_date  gender  year  month  day
0   tolu   23  chemistry   4.0     2012-12-02    male  2012     12    2
1   sola   22        law   3.0     2010-04-04  female  2010      4    4
2   caro   21    biology   3.2     2020-02-03    male  2020      2    3
3  yusuf   25    english   2.3     2014-03-06  female  2014      3    6
4   bola   27       data   5.0     2020-12-05  female  2020     12    5
5  yinka   28      agric   2.2     2015-10-04    male  2015     10    4
6  funmi   30   politics   4.3     2013-12-04  female  2013     12    4
7  adams   25   computer   4.7     2020-03-06    male  2020      3    6
8  ajayi   22    physics   4.2     2020-12-08  female  2020     12    8
9   paul   18      sport   1.0     2004-12-20    male  2004     12   20

In [ ]:
df.name.unique()

array(['tolu', 'sola', 'caro', 'yusuf', 'bola', 'yinka', 'funmi', 'adams',
       'ajayi', 'paul'], dtype=object)

In [ ]:
df.age.unique()

array([23, 22, 21, 25, 27, 28, 30, 18])

In [ ]:
df.department.unique()

array(['chemistry', 'law', 'biology', 'english', 'data', 'agric',
       'politics', 'computer', 'physics', 'sport'], dtype=object)

In [ ]:
df.gender.unique()

array(['male', 'female'], dtype=object)

In [ ]:
df.cgpa.unique()

array([4. , 3. , 3.2, 2.3, 5. , 2.2, 4.3, 4.7, 4.2, 1. ])

In [ ]:
df.admission_date.unique()

array(['2012-12-02T00:00:00.000000000', '2010-04-04T00:00:00.000000000',
       '2020-02-03T00:00:00.000000000', '2014-03-06T00:00:00.000000000',
       '2020-12-05T00:00:00.000000000', '2015-10-04T00:00:00.000000000',
       '2013-12-04T00:00:00.000000000', '2020-03-06T00:00:00.000000000',
       '2020-12-08T00:00:00.000000000', '2004-12-20T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [ ]:
df.year.unique()

array([2012, 2010, 2020, 2014, 2015, 2013, 2004])

In [ ]:
df.month.unique()

array([12,  4,  2,  3, 10])

In [ ]:
df.day.unique()

array([ 2,  4,  3,  6,  5,  8, 20])

In [ ]:
df.name.nunique()

10

In [ ]:
df.cgpa.nunique()

10

In [ ]:
df.gender.nunique()

2

In [ ]:
df.department.nunique()

10

In [ ]:
df.admission_date.nunique()

10

In [ ]:
df.gender.value_counts()

male      5
female    5
Name: gender, dtype: int64

In [ ]:
df.name.value_counts()

tolu     1
sola     1
caro     1
yusuf    1
bola     1
yinka    1
funmi    1
adams    1
ajayi    1
paul     1
Name: name, dtype: int64

In [ ]:
df.cgpa.value_counts()

4.0    1
3.0    1
3.2    1
2.3    1
5.0    1
2.2    1
4.3    1
4.7    1
4.2    1
1.0    1
Name: cgpa, dtype: int64

In [ ]:
df.admission_date.value_counts()

2012-12-02    1
2010-04-04    1
2020-02-03    1
2014-03-06    1
2020-12-05    1
2015-10-04    1
2013-12-04    1
2020-03-06    1
2020-12-08    1
2004-12-20    1
Name: admission_date, dtype: int64

In [ ]:
df.age.value_counts()

22    2
25    2
23    1
21    1
27    1
28    1
30    1
18    1
Name: age, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   name            10 non-null     object        
 1   age             10 non-null     int64         
 2   department      10 non-null     object        
 3   cgpa            10 non-null     float64       
 4   admission_date  10 non-null     datetime64[ns]
 5   gender          10 non-null     object        
 6   year            10 non-null     int64         
 7   month           10 non-null     int64         
 8   day             10 non-null     int64         
dtypes: datetime64[ns](1), float64(1), int64(4), object(3)
memory usage: 848.0+ bytes


In [ ]:
df.describe()

age       cgpa         year     month        day
count  10.00000  10.000000    10.000000  10.00000  10.000000
mean   24.10000   3.390000  2014.800000   8.20000   6.200000
std     3.60401   1.276671     5.370702   4.54117   5.138093
min    18.00000   1.000000  2004.000000   2.00000   2.000000
25%    22.00000   2.475000  2012.250000   3.25000   4.000000
50%    24.00000   3.600000  2014.500000  11.00000   4.500000
75%    26.50000   4.275000  2020.000000  12.00000   6.000000
max    30.00000   5.000000  2020.000000  12.00000  20.000000

In [ ]:
df.shape('row')

TypeError: ignored

In [ ]:
df.shape[0]

10

In [ ]:
df.shape[1]

9

In [ ]:
df.query("gender=='male'")



name  age department  cgpa admission_date gender  year  month  day
0   tolu   23  chemistry   4.0     2012-12-02   male  2012     12    2
2   caro   21    biology   3.2     2020-02-03   male  2020      2    3
5  yinka   28      agric   2.2     2015-10-04   male  2015     10    4
7  adams   25   computer   4.7     2020-03-06   male  2020      3    6
9   paul   18      sport   1.0     2004-12-20   male  2004     12   20

In [74]:
df['cgpa'].mean()

3.3899999999999997

In [75]:
df['cgpa'].sum()

33.9

In [76]:
df['cgpa'].min()

1.0

In [77]:
df['cgpa'].max()

5.0

In [78]:
df

name  age department  cgpa admission_date  gender  year  month  day
0   tolu   23  chemistry   4.0     2012-12-02    male  2012     12    2
1   sola   22        law   3.0     2010-04-04  female  2010      4    4
2   caro   21    biology   3.2     2020-02-03    male  2020      2    3
3  yusuf   25    english   2.3     2014-03-06  female  2014      3    6
4   bola   27       data   5.0     2020-12-05  female  2020     12    5
5  yinka   28      agric   2.2     2015-10-04    male  2015     10    4
6  funmi   30   politics   4.3     2013-12-04  female  2013     12    4
7  adams   25   computer   4.7     2020-03-06    male  2020      3    6
8  ajayi   22    physics   4.2     2020-12-08  female  2020     12    8
9   paul   18      sport   1.0     2004-12-20    male  2004     12   20

In [80]:
df.to_csv('student_details.csv', index=True)